# Generated by Django 4.1.2 on 2022-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=280, verbose_name='Conteudo')),
                ('data', models.DateField(verbose_name='Data')),
                ('like', models.IntegerField(verbose_name='Like')),
                ('visualizacao', models.IntegerField(verbose_name='Visualizacao')),
                ('retweet', models.IntegerField(verbose_name='Retweet')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('polaridade', models.IntegerField(verbose_name='Polaridade')),
                ('subjetividade', models.IntegerField(verbose_name='Subjetividade')),
            ],
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='termo',
            field=models.CharField(max_length=30, verbose_name='Pesquisa'),
        ),
    ]
