# Generated by Django 4.1.2 on 2022-10-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0002_tweet_alter_pesquisa_data_alter_pesquisa_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='termometromarcas.tweet'),
        ),
    ]
