# Generated by Django 4.1.2 on 2022-10-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0002_usuario_pesquisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pesquisas',
            field=models.ManyToManyField(blank=True, null=True, to='termometromarcas.pesquisa'),
        ),
    ]
