# Generated by Django 4.1.2 on 2022-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0002_remove_fisico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('desativo', 'Desativo')], default='ativo', max_length=255),
        ),
    ]
