# Generated by Django 4.1.2 on 2022-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0003_pesquisa_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='tweet',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='tweet',
            field=models.ManyToManyField(to='termometromarcas.tweet'),
        ),
    ]
