# Generated by Django 4.1.2 on 2022-10-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0005_geografico_tempo_usuario_alter_pesquisa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(max_length=15, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField(max_length=30, verbose_name='CPNJ')),
            ],
        ),
    ]
