# Generated by Django 4.1.2 on 2022-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometromarcas', '0006_fisico_juridico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='cnpj',
            field=models.BigIntegerField(verbose_name='CPNJ'),
        ),
    ]
